version: "3.7"
services:
  local:
    build: .
    image: backoffice_api
    container_name: backoffice_api_local
    ports:
      - 4002:4002
    volumes:
      - ./src:/src
    depends_on:
      - dataDb
    environment:
      NODE_ENV: local
    env_file:
      - .env
    entrypoint: "npm run dev"
    networks:
      - backoffice_network
      - plataforma_educativa_network
  dataDb:
    image: postgres:14.0-alpine
    container_name: backoffice_dataDb
    ports:
      - 5432
    restart: always
    environment:
      DATA_DB_NAME: data_backoffice
      DATA_DB_HOST: dpg-cookgru3e1ms73b7jdl0-a
      POSTGRES_USER: marisol
      POSTGRES_PASSWORD: 66qPTynlBto5XXE0MNUMk8pnjrKjiWkw
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./sql/1-schema/2022.05-schema.sql:/docker-entrypoint-initdb.d/1-schema-dataDb.sql
    networks:
      - backoffice_network
  
networks:
  backoffice_network:
    name: backoffice_network
  plataforma_educativa_network:
    external: true
